# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_client_id: 986416150345-85n43r6ib2pa60vqi4u3c2ei875l58h2.apps.googleusercontent.com
  google_client_secret: MuEEibgdb13N4Q7LJ5gdJRx

test:
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
